### ISSUE TITLE
Spider: Detroit Regional Convention Facility Authority

### ISSUE THREAD

**Issue by pjsier** [City-Bureau/city-scrapers-det#3]
URL: http://www.drcfa.org/upcoming-meetings
Spider Name: `det_regional_convention`
Agency Name: Detroit Regional Convention Facility Authority

See the [contribution guide](https://cityscrapers.org/docs/development/#contribute) for information on how to get started

Migrated from https://github.com/City-Bureau/city-scrapers/issues/850

**Comment by shf** [comment]
can I take this one?

**Comment by pjsier** [comment]
@shf sure! Assigning you now

**Comment by pjsier** [comment]
Closed by #6, thanks @shf!
