### ISSUE TITLE
Spider: Detroit Employment Solutions Corporation

### ISSUE THREAD

**Issue by pjsier** [City-Bureau/city-scrapers-det#4]
URL: https://www.descmiworks.com/about-us/public-meetings/
Spider Name: `det_employment_solutions`
Agency Name: Detroit Employment Solutions Corporation

See the [contribution guide](https://cityscrapers.org/docs/development/#contribute) for information on how to get started

Some information will need to be parsed from PDFs, so it could be useful to look at [`chi_human_relations`](https://github.com/City-Bureau/city-scrapers/blob/fbddf7cf785f261ea1829706dd58fc7ea5777a9a/city_scrapers/spiders/chi_human_relations.py) for an example of how to handle this

Migrated from https://github.com/City-Bureau/city-scrapers/issues/856

**Comment by maykonmenezes** [comment]
can i try this one?

**Comment by avelosa** [comment]
I would like to give this issue a shot :)

**Comment by pjsier** [comment]
@avelosa sounds great! Assigning you now. And I think only editors on the repo can assign people, but commenting gets you halfway there

**Comment by pjsier** [comment]
Closed by #5, thanks @avelosa!
